version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        build: ./docker
        volumes:
            - ./code:/code
        networks:
            - code-network
    db:
        image: postgres:10.1
        restart: always
        environment:
            - POSTGRES_DB=docker
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=""
        ports:
            - 5432:5432 
        networks:
            - code-network
networks:
    code-network:
        driver: bridge